version: 2.1.1
last_compiled: 2025-12-14 23:53:36

# ================================================
# Compiled with the following settings:
#
# To change these settings, run snapnia init to re-compile your project with the new settings.
# ================================================
profile: default
claude_code_commands: True
use_claude_code_subagents: True
snapnia_commands: False
standards_as_claude_code_skills: True
